apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: nodeapp
  namespace: argocd
spec:
  project: default

  source:
    repoURL: https://github.com/ChanPisey/project_cicd.git
    targetRevision: main
    path: gitops/charts/nodeapp
    helm:
      valueFiles:
        - values-prod.yaml

  destination:
    server: https://kubernetes.default.svc
    namespace: nodeapp

  syncPolicy:
    automated:
      prune: true
      selfHeal: true
    syncOptions:
      - CreateNamespace=true
